function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

const KEYWORDS: Record<string, string[]> = {
  java: [
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "void",
    "volatile",
    "while",
  ],
  javascript: [
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "let",
    "new",
    "null",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
  ],
  typescript: [
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "number",
    "return",
    "static",
    "string",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
  ],
  python: [
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "False",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "None",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "True",
    "try",
    "while",
    "with",
    "yield",
  ],
  cpp: [
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "class",
    "compl",
    "const",
    "constexpr",
    "continue",
    "default",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "register",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "template",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
    "xor",
    "xor_eq",
  ],
  sql: [
    "SELECT",
    "FROM",
    "WHERE",
    "INSERT",
    "INTO",
    "UPDATE",
    "DELETE",
    "CREATE",
    "TABLE",
    "DROP",
    "ALTER",
    "INDEX",
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "OUTER",
    "FULL",
    "CROSS",
    "ON",
    "AS",
    "AND",
    "OR",
    "NOT",
    "NULL",
    "IS",
    "IN",
    "EXISTS",
    "GROUP",
    "BY",
    "ORDER",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "DISTINCT",
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "PRIMARY",
    "KEY",
    "FOREIGN",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "DEFAULT",
    "VALUES",
    "SET",
    "UNION",
    "ALL",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "BETWEEN",
    "LIKE",
    "ASC",
    "DESC",
    "VIEW",
    "DATABASE",
    "SCHEMA",
    "TRUNCATE",
    "COMMIT",
    "ROLLBACK",
    "BEGIN",
    "TRANSACTION",
    "GRANT",
    "REVOKE",
    "CONSTRAINT",
    "AUTO_INCREMENT",
  ],
};

function highlightKeywords(code: string, language: string): string {
  const words = KEYWORDS[language] ?? KEYWORDS.javascript;
  const flags = language === "sql" ? "gi" : "g";
  const pattern = new RegExp(`\\b(${words.join("|")})\\b`, flags);
  return code.replace(pattern, '<span class="prep-code-kw">$1</span>');
}

function highlightStrings(code: string): string {
  return code
    .replace(/"(\\.|[^"\\])*"/g, '<span class="prep-code-str">$&</span>')
    .replace(/'(\\.|[^'\\])*'/g, '<span class="prep-code-str">$&</span>');
}

function highlightComments(code: string): string {
  return code
    .replace(/(\/\/[^\n]*)/g, '<span class="prep-code-cmt">$1</span>')
    .replace(/(#[^\n]*)/g, '<span class="prep-code-cmt">$1</span>');
}

function highlightNumbers(code: string): string {
  return code.replace(/\b(\d+\.?\d*)\b/g, '<span class="prep-code-num">$1</span>');
}

export function highlightPrepCode(code: string, language: string): string {
  const sqlComments = new Map<string, string>();
  let source = code;

  if (language === "sql") {
    let index = 0;
    source = source.replace(/(--[^\n]*)/g, (match) => {
      const key = `__SQLCMT_${index}__`;
      sqlComments.set(key, match);
      index += 1;
      return key;
    });
  }

  let html = escapeHtml(source);
  html = highlightComments(html);
  html = highlightStrings(html);
  html = highlightKeywords(html, language);
  html = highlightNumbers(html);

  for (const [key, comment] of sqlComments) {
    html = html.replace(key, `<span class="prep-code-cmt">${escapeHtml(comment)}</span>`);
  }

  return html;
}
